# Generated by Django 5.0.7 on 2024-09-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0001_squashed_0004_alter_cronjoblog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjoblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cronjoblog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
